name: bookia_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  pinput: ^5.0.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: DmSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400
